name: my_app
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.2.2
  dart_jsonwebtoken: ^3.4.1
  json_annotation: ^4.12.0
  sqlite3: ^3.3.1

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.0
  test: ^1.0.0
  build_runner: ^2.15.0
  json_serializable: ^6.14.0
